sudo: false
language: node_js
node_js:
- '4.2'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_install:
- npm install -g grunt-cli
- npm link
- npm link grunt-dactylographsy
notifications:
  email: false
env:
  global:
  - secure: jGqiGDLCtnY4aYQD6hIQ5zHk/nXzgHWNWbjx5JWce+bhPUXqipFR9Trk2oHKnrs9rjo0jL5I++ftJOgaETNMgNMRmCsfqaCd2i+yohdc0VUgDjtjDAxz9mxJyz6fHQ3c/DtHpi9+Wz9kGxE/7X/jRLuWVAx1eFdpJDzlqA7iKdd7RjA18q8gn1h72/A9XGMeNUSgdZbHaJOeQpIAvHAcdvh/zM+ZcONcXCnFzioWMCasSuKMXJXPEwA4tbaZo3RsnAeB7P/xpf38bL+Edtco5T4Be4WErP0DqF5t+jN/J/RyVkC/xihiEk5Yx+4xBiXTkJ1iXUVO7tNEFdxJsvLyux68LuZbffg+CYlZjRwCc8ZsEVvqfbjThfvWwT/zg0KijJCIBXW3gzKRddZTh+pls10cgFRg5EuX/3zFp9GXsxxOu+kAFViy8BBB3DbmehmV+1zaFDIvFDHjNv81S1nCA+7HI/pc/tCOfeKilr3wSKrkzZTfMNc06usUorbdb1SvwCJr11JQLBcaas2XqDe0PSolW6AfbzL/Eo5xVYbpGsvenlwjngiin5WkxiNeQ+DAJITflUICjLwiu9K+Ayvt98uWm7KVMktj5KkAKelLPYh3DmivfYpAQepunN/yd1bzuLhWAfwRpVXLEsUSfJCHsri4dt8aJJuzJvgBptAlsI0=
  - secure: tjYCuU1p+EYsfQVK2cBs7HtUSTkiQpJvaDrni1wmwdA/6SF5W08HnW/tKf/RLGdPyvwHjii35v+WGPUCBejUPt/Un0VAF9UZCQUjtx3ejKEEn8dLtpDMwrc/nM0v0xCSjGv6TgJgPG44xmirLEiJ7xFq8G3WTywQv6N1TKoOCoJtq132m0q/DyYCby8H5BTI1mhmSGyTBy/0LAkm1cdMU5zOJhLXLJa8pa7TbD5M7OvmdL3kVPuG6OZejFQZ5ZIsisIljB0yNDt+HYzhuTc6TDRx3kcHi5Z24wezMb3Hfy1R327mXHSQP1HVfCqZl8oRGsdtokaMKSWvv1tK8HV5lrScGxsxHg4+E+t+pz8GQqCGlfhZSipOvhaUllotmPkibn1OJrcndHDPHndMyeDHCXsZK09131CVIO8FFtqrd4HzeE9LHUCD/dEvL5r1+EDi5hdTbn+qBlPoUzbKyW4/OK3KK64+2//DxW5140fMmFU5Z8uSfs0gzMJdgHeA87kdJpce3JNnBWxCq5PpLN+vZRqoBDjcaCilLhT+me5uKNoYUQRXj2d5KOFbVCluiaFEPYvcpfSYD60LJyZx7HJB13r4y/5Ft9UIBnwHkDho558Fjro39eZ8sKb9N9tOC8z1AVGV7yApsB7RiEURHAPv++ewZmH6KBgcJxmmTyX60H0=
